### ISSUE TITLE
Drop the big-O, Move to more general asymptothic notation

### ISSUE THREAD

**Issue by Tadaboody** [tonybaloney/notations#1]
While it's true for example that a 1-loop function is runs in time that is `O(n)`, it actually runs in `\Tetha(n)`. the distinction is between asymptotic `<=` and `==`. By dropping big-O in naming and pretty much leaving stuff as they are you can express much more of the asymptotic hierarchy, namely small-o (`<`) big and small omega (`<=`,`<` respectively) and theta (`==`).

**Comment by tonybaloney** [comment]
thanks @Tadaboody done in 0.2.0
